# Generated by Django 6.0.3 on 2026-05-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
    ]
