# Generated by Django 6.0.3 on 2026-05-22 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_est_actif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medecin_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_assignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='personnel_medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_enregistres', to=settings.AUTH_USER_MODEL),
        ),
    ]
