# Generated by Django 6.0.3 on 2026-05-23 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_medecin_responsable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medecin_responsable',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='personnel_medical',
        ),
        migrations.AddField(
            model_name='patient',
            name='medecin_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_en_charge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='medecin_generaliste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssignationInfirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soins_a_faire', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('infirmier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_soins', to=settings.AUTH_USER_MODEL)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations_infirmier_faites', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations_infirmier', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Assignation infirmier',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AssignationMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('service', models.CharField(blank=True, max_length=100)),
                ('date_assignation', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('medecin_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations_recues', to=settings.AUTH_USER_MODEL)),
                ('medecin_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations_faites', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations_medecin', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Assignation médecin',
                'ordering': ['-date_assignation'],
            },
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('observations', models.TextField(blank=True)),
                ('date_soin', models.DateTimeField(auto_now_add=True)),
                ('assignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='patients.assignationinfirmier')),
                ('infirmier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins_effectues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soin',
                'ordering': ['-date_soin'],
            },
        ),
    ]
