# Generated by Django 6.0.3 on 2026-05-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_medecin_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
