# Generated by Django 6.0.3 on 2026-05-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_est_actif_alter_consultation_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='est_actif',
        ),
    ]
