# Generated by Django 6.0.5 on 2026-05-12 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(choices=[('BIOLOGIE', 'Biologie'), ('RADIOLOGIE', 'Radiologie'), ('ECHOGRAPHIE', 'Échographie'), ('SCANNER', 'Scanner'), ('IRM', 'IRM'), ('ECG', 'ECG'), ('AUTRE', 'Autre')], max_length=20)),
                ('nom_examen', models.CharField(max_length=255)),
                ('date_prescription', models.DateField()),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('laboratoire', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Examen médical',
                'verbose_name_plural': 'Examens médicaux',
                'ordering': ['-date_prescription'],
            },
        ),
    ]
