# Generated by Django 6.0.3 on 2026-05-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_est_actif_alter_consultation_patient'),
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens', to='consultations.consultation'),
        ),
    ]
