# Generated by Django 6.0.3 on 2026-05-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0002_examen_est_actif_alter_examen_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='est_actif',
        ),
    ]
