# Generated by Django 6.0.3 on 2026-05-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0003_remove_examen_est_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REALISE', 'Réalisé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
