# Generated by Django 6.0.5 on 2026-05-12 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_resultat', models.DateField()),
                ('contenu', models.TextField()),
                ('conclusion', models.TextField()),
                ('est_normal', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='examens.examen')),
            ],
            options={
                'verbose_name': "Résultat d'examen",
                'verbose_name_plural': "Résultats d'examens",
                'ordering': ['-date_resultat'],
            },
        ),
    ]
