# Generated by Django 6.0.3 on 2026-05-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0002_examen_est_actif_alter_examen_consultation'),
        ('resultats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resultat', to='examens.examen'),
        ),
    ]
