# Generated by Django 6.0.3 on 2026-05-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultats', '0002_resultat_est_actif_alter_resultat_examen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultat',
            name='est_actif',
        ),
    ]
