# Generated by Django 6.0.3 on 2026-05-14 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField()),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('motif_admission', models.TextField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SORTI', 'Sorti'), ('TRANSFERE', 'Transféré'), ('DECEDE', 'Décédé')], default='EN_COURS', max_length=20)),
                ('motif_sortie', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('lit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to='services.lit')),
                ('medecin_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Hospitalisation',
                'verbose_name_plural': 'Hospitalisations',
                'ordering': ['-date_entree'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_observation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='hospitalisations.hospitalisation')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'ordering': ['-date_observation'],
            },
        ),
    ]
